staging:
  adapter: mysql2
  database: ortek_staging
  pool: 5
  timeout: 5000
  username: root
  password: root

development:
  adapter: mysql2
  database: ortek_pro
  pool: 5
  timeout: 5000
  username: root
  password: qazplm123